### ISSUE TITLE
ppm is not sRGB

### ISSUE THREAD

**Issue by malaterre** [vbaderks/netpbm-wic-codec#36]
I think the toplevel README would at least reference the original intend of the ppm file format specification:

* https://netpbm.sourceforge.net/doc/ppm.html

> In the raster, the sample values are "nonlinear." They are proportional to the intensity of the ITU-R Recommendation BT.709 red, green, and blue in the pixel, adjusted by the BT.709 gamma transfer function. (That transfer function specifies a gamma number of 2.2 and has a linear section for small intensities). A value of Maxval for all three samples represents CIE D65 white and the most intense color in the color universe of which the image is part (the color universe is all the colors in all images to which this image might be compared).
> 
> BT.709's range of channel values (16-240) is irrelevant to PPM.
> 
> ITU-R Recommendation BT.709 is a renaming of the former CCIR Recommendation 709. When CCIR was absorbed into its parent organization, the ITU, ca. 2000, the standard was renamed. This document once referred to the standard as CIE Rec. 709, but it isn't clear now that CIE ever sponsored such a standard.
> 
> Note that another popular color space is the newer sRGB. A common variation from PPM is to substitute this color space for the one specified. You can use pnmgamma to convert between this variation and true PPM.
> 
> Note that a common variation from the PPM format is to have the sample values be "linear," i.e. as specified above except without the gamma adjustment. pnmgamma takes such a PPM variant as input and produces a true PPM as output.

**Comment by vbaderks** [comment]
This has been resolved with #49
