### ISSUE TITLE
'qualified' winrt in line 8 of pnm_header_test.cpp?

### ISSUE THREAD

**Issue by vasilich-tregub** [vbaderks/netpbm-wic-codec#39]
https://github.com/vbaderks/netpbm-wic-codec/blob/38bce14aff02920dfe6ab66e9fc2b3db74004bd6/test/pnm_header_test.cpp#L8

maybe it would be better to write here

import test.winrt;

instead of just

import winrt;

**Comment by vbaderks** [comment]
Thanks for the report. Should be indeed import test.winrt;

**Comment by vbaderks** [comment]
This has been resolved with #40
