### ISSUE TITLE
the use of the 'WINRT_NO_MAKE_DETECTION' define in the project

### ISSUE THREAD

**Issue by vasilich-tregub** [vbaderks/netpbm-wic-codec#41]
Is it absolutely necessary to mark implementation classes of this project 'final'? When doing so, you need to define the symbol 'WINRT_NO_MAKE_DETECTION', and the documentation strongly recommends to not define this symbol (https://learn.microsoft.com/en-us/windows/uwp/cpp-and-winrt-apis/macros#winrt_no_make_detection). The other document (https://learn.microsoft.com/en-us/windows/uwp/cpp-and-winrt-apis/diag-direct-alloc#the-solution-with-cwinrt-20) explains that there is no need to mark the whole implementation class 'final', as the instantiated type will always be final. Again, any virtual functions in your implementation can be marked as final, if need be. So, if it is possible to avoid marking the whole classes as final, the project would conform to the documentation recommendation against the 'WINRT_NO_MAKE_DETECTION' define.

**Comment by vbaderks** [comment]
I always make my classes by default final to mark explicitly that the class is not designed to be derived from. It prevents that a virtual destructor or protected destructor needs to be added. I see it as one of the defaults that C++ gets wrong. 
(C++ gets more defaults wrong, see for example: https://www.think-cell.com/en/career/devblog/trip-report-spring-iso-cpp-meeting-in-tokyo-japan). Static analyzers such as Jetbrains Resharper will also flag classes that can be final, but aren't.

C++/WinRT supports that my implementation classes are final, but as you stated this requires that WINRT_NO_MAKE_DETECTION is defined. COM classes always need to be allocated on the heap and C++/WinRT provides the method winrt::make which is intended to be used to perform this heap allocation. C++/WinRT uses a trick to create a linker error when trying to allocate an implementation class without using the winrt::make method. This trick is to derive from the implementation class and to provide the missing method. To make this trick work implementation classes cannot be final. 

I re-evaluated the current design between using the default C++/WinRT model vs using final on the implementation classed and think that using the C++/WinRT defaults (not using final) may be more clear for people that use this project as an example how to create classic COM objects with C++/WinRT.

Note: Applying final to the virtual methods would only helpful in situations that would allow a direct method call for better performance. As COM interfaces are always called by means of the v-table, there is no benefit of doing this.

**Comment by vbaderks** [comment]
Resolved with #42
